<?php

namespace ContainerRNxxfFu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BpYHqrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bp_yHqr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bp_yHqr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\ProduitsController::add' => ['privates', '.service_locator.chP98y.', 'get_ServiceLocator_ChP98y_Service', true],
            'App\\Controller\\Admin\\ProduitsController::delete' => ['privates', '.service_locator.iF0gfUS', 'get_ServiceLocator_IF0gfUSService', true],
            'App\\Controller\\Admin\\ProduitsController::edit' => ['privates', '.service_locator.Xj0Pp.F', 'get_ServiceLocator_Xj0Pp_FService', true],
            'App\\Controller\\Admin\\ProduitsController::index' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ApiController::index' => ['privates', '.service_locator.cEop0VK', 'get_ServiceLocator_CEop0VKService', true],
            'App\\Controller\\CatalogueController::acceuil' => ['privates', '.service_locator.dMqg9WR', 'get_ServiceLocator_DMqg9WRService', true],
            'App\\Controller\\CatalogueController::categorie' => ['privates', '.service_locator.J6JEzNf', 'get_ServiceLocator_J6JEzNfService', true],
            'App\\Controller\\CatalogueController::produit' => ['privates', '.service_locator.sA20_cM', 'get_ServiceLocator_SA20CMService', true],
            'App\\Controller\\NavController::bandeau' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\NavController::nav' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\NavController::navAdmin' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\PanierController::add' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\PanierController::delete' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\PanierController::index' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\PanierController::remove' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\PanierController::validation' => ['privates', '.service_locator.45rQau1', 'get_ServiceLocator_45rQau1Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.kkmhh0R', 'get_ServiceLocator_Kkmhh0RService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\ProduitsController:add' => ['privates', '.service_locator.chP98y.', 'get_ServiceLocator_ChP98y_Service', true],
            'App\\Controller\\Admin\\ProduitsController:delete' => ['privates', '.service_locator.iF0gfUS', 'get_ServiceLocator_IF0gfUSService', true],
            'App\\Controller\\Admin\\ProduitsController:edit' => ['privates', '.service_locator.Xj0Pp.F', 'get_ServiceLocator_Xj0Pp_FService', true],
            'App\\Controller\\Admin\\ProduitsController:index' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\ApiController:index' => ['privates', '.service_locator.cEop0VK', 'get_ServiceLocator_CEop0VKService', true],
            'App\\Controller\\CatalogueController:acceuil' => ['privates', '.service_locator.dMqg9WR', 'get_ServiceLocator_DMqg9WRService', true],
            'App\\Controller\\CatalogueController:categorie' => ['privates', '.service_locator.J6JEzNf', 'get_ServiceLocator_J6JEzNfService', true],
            'App\\Controller\\CatalogueController:produit' => ['privates', '.service_locator.sA20_cM', 'get_ServiceLocator_SA20CMService', true],
            'App\\Controller\\NavController:bandeau' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\NavController:nav' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\NavController:navAdmin' => ['privates', '.service_locator.DFyL8OH', 'get_ServiceLocator_DFyL8OHService', true],
            'App\\Controller\\PanierController:add' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\PanierController:delete' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\PanierController:index' => ['privates', '.service_locator.vRUAr7Q', 'get_ServiceLocator_VRUAr7QService', true],
            'App\\Controller\\PanierController:remove' => ['privates', '.service_locator.ViXcClx', 'get_ServiceLocator_ViXcClxService', true],
            'App\\Controller\\PanierController:validation' => ['privates', '.service_locator.45rQau1', 'get_ServiceLocator_45rQau1Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.kkmhh0R', 'get_ServiceLocator_Kkmhh0RService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\ProduitsController::add' => '?',
            'App\\Controller\\Admin\\ProduitsController::delete' => '?',
            'App\\Controller\\Admin\\ProduitsController::edit' => '?',
            'App\\Controller\\Admin\\ProduitsController::index' => '?',
            'App\\Controller\\ApiController::index' => '?',
            'App\\Controller\\CatalogueController::acceuil' => '?',
            'App\\Controller\\CatalogueController::categorie' => '?',
            'App\\Controller\\CatalogueController::produit' => '?',
            'App\\Controller\\NavController::bandeau' => '?',
            'App\\Controller\\NavController::nav' => '?',
            'App\\Controller\\NavController::navAdmin' => '?',
            'App\\Controller\\PanierController::add' => '?',
            'App\\Controller\\PanierController::delete' => '?',
            'App\\Controller\\PanierController::index' => '?',
            'App\\Controller\\PanierController::remove' => '?',
            'App\\Controller\\PanierController::validation' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\ProduitsController:add' => '?',
            'App\\Controller\\Admin\\ProduitsController:delete' => '?',
            'App\\Controller\\Admin\\ProduitsController:edit' => '?',
            'App\\Controller\\Admin\\ProduitsController:index' => '?',
            'App\\Controller\\ApiController:index' => '?',
            'App\\Controller\\CatalogueController:acceuil' => '?',
            'App\\Controller\\CatalogueController:categorie' => '?',
            'App\\Controller\\CatalogueController:produit' => '?',
            'App\\Controller\\NavController:bandeau' => '?',
            'App\\Controller\\NavController:nav' => '?',
            'App\\Controller\\NavController:navAdmin' => '?',
            'App\\Controller\\PanierController:add' => '?',
            'App\\Controller\\PanierController:delete' => '?',
            'App\\Controller\\PanierController:index' => '?',
            'App\\Controller\\PanierController:remove' => '?',
            'App\\Controller\\PanierController:validation' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
