<?php

namespace ContainerRNxxfFu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xj0Pp_FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xj0Pp.F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xj0Pp.F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produit' => ['privates', '.errored..service_locator.Xj0Pp.F.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.Xj0Pp.F": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'em' => '?',
            'produit' => 'App\\Entity\\Produit',
            'slugger' => '?',
        ]);
    }
}
