<?php

namespace ContainerRNxxfFu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_45rQau1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.45rQau1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.45rQau1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adresses' => ['privates', 'App\\Repository\\AdresseRepository', 'getAdresseRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'adresses' => 'App\\Repository\\AdresseRepository',
            'entityManager' => '?',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
