<?php

namespace ContainerRNxxfFu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J6JEzNfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J6JEzNf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J6JEzNf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.J6JEzNf.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.J6JEzNf": it needs an instance of "App\\Entity\\Categorie" but this type has been excluded in "config/services.yaml".'],
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'photoRepository' => ['privates', 'App\\Repository\\PhotoRepository', 'getPhotoRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'photoRepository' => 'App\\Repository\\PhotoRepository',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
        ]);
    }
}
