<?php

namespace ContainerRNxxfFu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CEop0VKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cEop0VK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cEop0VK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pictureService' => ['privates', 'App\\Service\\PictureService', 'getPictureServiceService', true],
        ], [
            'pictureService' => 'App\\Service\\PictureService',
        ]);
    }
}
