<?php

namespace ContainerRNxxfFu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduitsFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ProduitsFormType' shared autowired service.
     *
     * @return \App\Form\ProduitsFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ProduitsFormType.php';

        return $container->privates['App\\Form\\ProduitsFormType'] = new \App\Form\ProduitsFormType();
    }
}
