<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQCqWTkx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQCqWTkx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQCqWTkx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQCqWTkx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQCqWTkx\App_KernelDevDebugContainer([
    'container.build_hash' => 'QCqWTkx',
    'container.build_id' => '64305bda',
    'container.build_time' => 1684219633,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQCqWTkx');
