<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerInfC14H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerInfC14H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerInfC14H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerInfC14H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerInfC14H\App_KernelDevDebugContainer([
    'container.build_hash' => 'InfC14H',
    'container.build_id' => 'e6e880b4',
    'container.build_time' => 1681724548,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerInfC14H');
